[package]
name = "bugle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bbscope = "0.1.4"
binread = "2.2"
bitflags = "1"
bit-vec = "0.6.3"
chrono = "0.4.23"
crc32fast = "1"
flate2 = "1"
fltk = { version = "1.3.27", features = ["fltk-bundled"] }
fltk-table = "0.2.1"
fltk-webview = "0.2.16"
futures = "0.3"
governor = "0.4.2"
lazy_static = "1"
linked-hash-map = "0.5.6"
nom = "7"
regex = "1.6"
reqwest = { version = "0.11", features = ["gzip", "json"] }
rusqlite = { version = "0.28", features = ["bundled"] }
rust-ini = "0.18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
slog = "2"
slog-async = "2"
slog-term = "2"
steamlocate = "1"
steamy-vdf = "0.2.0"
strum = "0.24"
strum_macros = "0.24"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
ucs2 = "0.3.2"
urlencoding = "2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["mswsock", "winsock2"] }
